export const FETCH_INFO = 'BLOG/FETCH_INFO';
export const FETCH_INFO_SUCCESS = 'BLOG/FETCH_INFO_SUCCESS';
export const FETCH_INFO_FAIL = 'BLOG/FETCH_INFO_FAIL';
export const FETCH_POSTS = 'BLOG/FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'BLOG/FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'BLOG/FETCH_POSTS_FAIL';
export const DELETE_ALL_POSTS = 'BLOG/DELETE_ALL_POSTS';
